import type { Transaction } from './types';

export const mockTransactions: Transaction[] = [
  {
    id: 'TXN-9F2A41C8',
    date: 'May 14, 2026 · 09:42',
    description: 'Premium Annual — auto-renewal',
    amount: 119.88,
    currency: 'USD',
    paymentMethod: { brand: 'visa', last4: '4242' },
    status: 'completed',
    invoice: 'ready',
  },
  {
    id: 'TXN-9F2A40B1',
    date: 'May 14, 2026 · 09:31',
    description: 'Standard Monthly — auto-renewal',
    amount: 15.99,
    currency: 'USD',
    paymentMethod: { brand: 'mastercard', last4: '8810' },
    status: 'failed',
    invoice: 'disabled',
  },
  {
    id: 'TXN-9F2A3F77',
    date: 'May 14, 2026 · 08:55',
    description: 'Family Plan — auto-renewal',
    amount: 22.99,
    currency: 'USD',
    paymentMethod: { brand: 'visa', last4: '9920' },
    status: 'failed',
    invoice: 'disabled',
  },
  {
    id: 'TXN-9F2A3E20',
    date: 'May 14, 2026 · 08:12',
    description: 'Premium Monthly — auto-renewal',
    amount: 17.99,
    currency: 'USD',
    paymentMethod: { brand: 'amex', last4: '1004' },
    status: 'retrying',
    invoice: 'disabled',
  },
  {
    id: 'TXN-9F2A3CB4',
    date: 'May 13, 2026 · 22:08',
    description: 'Premium Annual — auto-renewal',
    amount: 119.88,
    currency: 'USD',
    paymentMethod: { brand: 'visa', last4: '4242' },
    status: 'completed',
    invoice: 'generating',
  },
  {
    id: 'TXN-9F2A3A91',
    date: 'May 13, 2026 · 19:47',
    description: '4K Add-on — purchase',
    amount: 4.99,
    currency: 'USD',
    paymentMethod: { brand: 'apple_pay' },
    status: 'pending',
    invoice: 'disabled',
  },
  {
    id: 'TXN-9F2A38EE',
    date: 'May 13, 2026 · 17:23',
    description: 'Standard Monthly — auto-renewal',
    amount: 15.99,
    currency: 'USD',
    paymentMethod: { brand: 'paypal' },
    status: 'completed',
    invoice: 'ready',
  },
  {
    id: 'TXN-9F2A371D',
    date: 'May 13, 2026 · 14:02',
    description: 'Family Plan — auto-renewal',
    amount: 22.99,
    currency: 'USD',
    paymentMethod: { brand: 'mastercard', last4: '8810' },
    status: 'failed',
    invoice: 'disabled',
  },
  {
    id: 'TXN-9F2A3502',
    date: 'May 13, 2026 · 11:18',
    description: 'Premium Monthly — auto-renewal',
    amount: 17.99,
    currency: 'USD',
    paymentMethod: { brand: 'visa', last4: '4242' },
    status: 'completed',
    invoice: 'ready',
  },
  {
    id: 'TXN-9F2A3399',
    date: 'May 13, 2026 · 08:04',
    description: 'Basic Monthly — auto-renewal',
    amount: 9.99,
    currency: 'USD',
    paymentMethod: { brand: 'paypal' },
    status: 'completed',
    invoice: 'ready',
  },
  {
    id: 'TXN-9F2A3155',
    date: 'May 12, 2026 · 21:36',
    description: 'Basic Monthly — auto-renewal',
    amount: 9.99,
    currency: 'USD',
    paymentMethod: { brand: 'visa', last4: '9920' },
    status: 'completed',
    invoice: 'ready',
  },
  {
    id: 'TXN-9F2A2FC0',
    date: 'May 12, 2026 · 18:22',
    description: 'Premium Annual — auto-renewal',
    amount: 119.88,
    currency: 'USD',
    paymentMethod: { brand: 'amex', last4: '1004' },
    status: 'completed',
    invoice: 'ready',
  },
  {
    id: 'TXN-9F2A2DB2',
    date: 'May 12, 2026 · 15:51',
    description: 'Standard Monthly — auto-renewal',
    amount: 15.99,
    currency: 'USD',
    paymentMethod: { brand: 'mastercard', last4: '8810' },
    status: 'completed',
    invoice: 'ready',
  },
  {
    id: 'TXN-9F2A2BAA',
    date: 'May 12, 2026 · 12:09',
    description: 'Family Plan — auto-renewal',
    amount: 22.99,
    currency: 'USD',
    paymentMethod: { brand: 'visa', last4: '4242' },
    status: 'pending',
    invoice: 'disabled',
  },
  {
    id: 'TXN-9F2A2987',
    date: 'May 12, 2026 · 09:45',
    description: '4K Add-on — purchase',
    amount: 4.99,
    currency: 'USD',
    paymentMethod: { brand: 'apple_pay' },
    status: 'completed',
    invoice: 'ready',
  },
  {
    id: 'TXN-9F2A2755',
    date: 'May 11, 2026 · 22:13',
    description: 'Premium Annual — auto-renewal',
    amount: 119.88,
    currency: 'USD',
    paymentMethod: { brand: 'visa', last4: '9920' },
    status: 'failed',
    invoice: 'disabled',
  },
  {
    id: 'TXN-9F2A2522',
    date: 'May 11, 2026 · 18:30',
    description: 'Standard Monthly — auto-renewal',
    amount: 15.99,
    currency: 'USD',
    paymentMethod: { brand: 'apple_pay' },
    status: 'completed',
    invoice: 'ready',
  },
];
